name: Update GitHub Wiki

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: snok/install-poetry@v1

      - run: poetry install
      - run: poetry add pdoc3 --dev
      - run: poetry run pdoc --force -o docs PACKAGE_NAME
      - run: mv docs/PACKAGE_NAME/index.md docs/PACKAGE_NAME/Home.md

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs/PACKAGE_NAME"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}